POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "full_name": "Johnhhhh Doe",
  "email": "user@user.com",
  "phone_number": "123-456-7890",
  "is_blocked": false,
  "two_factor_auth": false,
  "password": "user"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"login": "user@user.com",
"password": "user"
}

###
POST http://localhost:8080/api/users/4/accounts
Content-Type: application/json

{
  "currency": "USD",
  "name": "Account 3"
}

###
POST http://localhost:8080/api/users/4/credit
Content-Type: application/json

{
  "account_id": 3,
  "term": "MONTH_3",
  "payment_type": "MANUAL",
  "amount_given": 5000.0,
  "is_notification_enabled": false
}