POST https://tofi.onrender.com/api/auth/register
Content-Type: application/json

{
  "full_name": "Johnhhhh Doe",
  "email": "user2@user.com",
  "phone_number": "123-456-7890",
  "is_blocked": false,
  "two_factor_auth": false,
  "password": "user"
}